language: c++
compiler: gcc

before_script:
        - cmake .
        - cmake --build .
        - cmake --build . --target package
script:
        - make

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T cmake_train.deb -udustydumb:$BINTRAY_API_KEY "https://api.bintray.com/content/dustydumb/cmake_task/cmake_try/$TRAVIS_BUILD_NUMBER/cmake_train.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
